### ISSUE TITLE
Render tiger:reviewed=aerial and name in some way

### ISSUE THREAD

**Issue by ward** [watmildon/TIGERMap#13]
Since [you consolidated](https://community.openstreetmap.org/t/consolidating-values-of-tiger-reviewed/109890) `tiger:reviewed` values to `no`, `aerial`, and `name` (and maybe `yes`), would it make sense to show `aerial` and `name` in some way?

I find it easy to armchair map my area from `no` to `aerial`, but for names I'll have to keep the county GIS on the side or pass by in person. I do eventually want to change those `aerial`s to complete removal though.

**Comment by watmildon** [comment]
Yes! A lovely improvement I've been chipping away at. Thanks for opening this so I don't lose track of it. I will probably include all `tiger:reviewed=*` objects so that you can even filter down to `yes`. This will require tweaks to the tile generation and to the filtering and layer portion of the site. Totally doable I just need to find the time. Maybe sometime next week?

**Comment by watmildon** [comment]
I think I have the changes in place to that you can have a filter like `tiger:reviewed=aerial;highway`. The site should be updated shortly but will need a data update which should run later tonight. I'll check back in the morning.

**Comment by watmildon** [comment]
Alright, we have data and filtering in place so that this now works: https://watmildon.github.io/TIGERMap/?filter=tiger%253Areviewed%21%253Dno#map=8.79/48.2219/-117.6197
